name: Update Playlist

on:
  push:
    paths:
      - 'playlist.json' # Assuming the playlist file is in the root directory
      - 'update_playlist.yml' # Adjust paths if necessary

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update playlist file
        run: |
          echo '[' > playlist_temp.json # Create temporary file
          echo "  \"https://cdn.glitch.me/1780eae4-2681-418a-b256-59d3398b90a7/lityanandha.mov?v=1714986982660\"," >> playlist_temp.json # Replace with your CDN URLs
          echo "  \"https://cdn.glitch.me/1780eae4-2681-418a-b256-59d3398b90a7/lityanandha.mov?v=1714986982660\"" >> playlist_temp.json
          echo ']' >> playlist_temp.json
          mv playlist_temp.json playlist.json # Replace the original playlist file with the updated one
          
